using SHIELDON.Domain.Enums;

namespace SHIELDON.Domain.Entities;

/// <summary>
/// Records a single anti-cheating violation detected during an exam attempt.
/// 
/// Violations are detected client-side by the Anti-Cheating Engine and persisted
/// here for tutor review in the monitoring dashboard (Phase 5).
///
/// Multiple violations per attempt are expected. Each violation has a Type (what
/// happened), a Severity (how serious), and a human-readable Description.
/// </summary>
public class ViolationLog
{
    public Guid Id { get; set; }

    // ── Attempt Context ───────────────────────────────────────────────────────

    /// <summary>FK → ExamAttempt. The active attempt during which the violation occurred.</summary>
    public Guid AttemptId { get; set; }

    /// <summary>FK → User (Student). Denormalized for faster querying in monitoring dashboard.</summary>
    public Guid StudentId { get; set; }

    /// <summary>FK → Exam. Denormalized for easy exam-level violation queries.</summary>
    public Guid ExamId { get; set; }

    /// <summary>FK → Course. Denormalized for easy course-level violation queries.</summary>
    public Guid CourseId { get; set; }

    // ── Violation Details ─────────────────────────────────────────────────────

    /// <summary>Classifies the violation type (TabSwitch, FullScreenExit, etc.).</summary>
    public ViolationType Type { get; set; }

    /// <summary>Severity level used for strike score calculation (Minor=0.5, Medium=1.0, Critical=1.0).</summary>
    public ViolationSeverity Severity { get; set; }

    /// <summary>Human-readable description of the violation, generated by the Anti-Cheat Engine.</summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>UTC timestamp of when the violation occurred (client-reported).</summary>
    public DateTime OccurredAt { get; set; }

    /// <summary>
    /// True if this violation was the final trigger that caused an automatic force-submit.
    /// At most one record per attempt will have this set to true.
    /// </summary>
    public bool WasAutoSubmit { get; set; }

    /// <summary>UTC timestamp of when this record was persisted to the database.</summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // ── Navigation Properties ─────────────────────────────────────────────────

    public ExamAttempt? Attempt { get; set; }
    public User? Student { get; set; }
    public Exam? Exam { get; set; }
    public Course? Course { get; set; }
}
